### ISSUE TITLE
There are two node_modules folders - though the project works fine.

### ISSUE THREAD

**Issue by cuddleofdeath** [cuddleofdeath/devblog#1]
I initialized the repo, then I created the react app. An empty project was essentially commited at this point.
Later, I installed react-icons, which created an issue and I'm not sure what the safest method to solve it would be.
The issue: There is now a node_modules folder inside the root of the project, as well as another node_modules folder that is within the blog folder.

**I am wondering what the smartest way to go about resolving this is that wouldn't result in breaking anything. Right now it functions, but the two node_modules folders irked me.**

**Comment by georgeat8** [comment]
Well, there is no reason to have just that `package.json` at root with only one dependency (`react-icons` in your case), so moving everything to root level should be fine, as in having the `blog` folder as your starting point for `root`, not a separate folder

**Comment by georgeat8** [comment]
You should just move the blog folder from a subfolder scope to the root scope, as in instead of having `./blog/{source}` => `./{source}`

That additional `package.json` might have been triggered because you `npm install` outside of your source code, where there wasn't a `package` file already.

**Comment by cuddleofdeath** [comment]
> You should just move the blog folder from a subfolder scope to the root scope, as in instead of having `./blog/{source}` => `./{source}`
> 
> That additional `package.json` might have been triggered because you `npm install` outside of your source code, where there wasn't a `package` file already.

Thank you very much! This helped, no issues at all!
